version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/MAGICFRONTEND
    ports:
      - 3000:3000
    image: app:react
    container_name: magicfront_container
    command: npm start